## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Vaini,TO,78.96,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
1,1,Puerto Ayora,EC,75.16,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
2,3,Kapaa,US,85.98,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
3,9,Atuona,PF,76.87,few clouds,-9.8000,-139.0333,Villa Enata
4,16,Jamestown,US,78.19,few clouds,42.0970,-79.2353,Hampton Inn & Suites Jamestown

In [6]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]
nvacation_df = pd.DataFrame(vacation_df)
nvacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Vaini,TO,78.96,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
1,1,Puerto Ayora,EC,75.16,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
2,3,Kapaa,US,85.98,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
3,9,Atuona,PF,76.87,few clouds,-9.8000,-139.0333,Villa Enata
4,16,Jamestown,US,78.19,few clouds,42.0970,-79.2353,Hampton Inn & Suites Jamestown

In [7]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[nvacation_df['City'] == 'Trebinje']
vacation_end = vacation_df.loc[nvacation_df['City'] == 'Trebinje']
vacation_stop1 = vacation_df.loc[nvacation_df['City'] == 'Diffa']
vacation_stop2 = vacation_df.loc[nvacation_df['City'] == 'Dwarka'] 
vacation_stop3 = vacation_df.loc[nvacation_df['City'] == 'Dingle']

In [14]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start['Lat'].to_numpy()[0] , vacation_start['Lng'].to_numpy()[0]
end = vacation_end['Lat'].to_numpy()[0] , vacation_end['Lng'].to_numpy()[0]
stop1 = vacation_stop1['Lat'].to_numpy()[0] , vacation_stop1['Lng'].to_numpy()[0]
stop2 = vacation_stop2['Lat'].to_numpy()[0] , vacation_stop2['Lng'].to_numpy()[0]
stop3 = vacation_stop3['Lat'].to_numpy()[0] , vacation_stop3['Lng'].to_numpy()[0]

In [15]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
import gmaps
import gmaps.datasets

# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
start2end_via_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(start2end_via_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,36,Trebinje,BA,80.94,clear sky,42.7119,18.3442,Hotel AÄimoviÄ
1,573,Diffa,NE,83.93,overcast clouds,13.3154,12.6113,ProDAF/Diffa
2,441,Dwarka,IN,80.71,broken clouds,22.2394,68.9678,Hotel Narayan Avezika Comfort
3,309,Dingle,PH,78.01,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
4,36,Trebinje,BA,80.94,clear sky,42.7119,18.3442,Hotel AÄimoviÄ

In [18]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]
itinerary_df = pd.DataFrame(itinerary_df)
itinerary_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,36,Trebinje,BA,80.94,clear sky,42.7119,18.3442,Hotel AÄimoviÄ
1,573,Diffa,NE,83.93,overcast clouds,13.3154,12.6113,ProDAF/Diffa
2,441,Dwarka,IN,80.71,broken clouds,22.2394,68.9678,Hotel Narayan Avezika Comfort
3,309,Dingle,PH,78.01,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
4,36,Trebinje,BA,80.94,clear sky,42.7119,18.3442,Hotel AÄimoviÄ

In [23]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
center = (30,30)
fig = gmaps.figure(center=center, zoom_level=2)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))